insert into tblBook (bookSeq,bookName,publisherSeq) values (1,'린 분석',4);
insert into tblBook (bookSeq,bookName,publisherSeq) values (2,'1일 1로그 100일 완성 IT 지식',2);
insert into tblBook (bookSeq,bookName,publisherSeq) values (3,'Clean Code(클린 코드)',2);
insert into tblBook (bookSeq,bookName,publisherSeq) values (4,'스프링 인 액션[5판]',7);
insert into tblBook (bookSeq,bookName,publisherSeq) values (5,'오늘부터 개발자',5);
insert into tblBook (bookSeq,bookName,publisherSeq) values (6,'IT 엔지니어를 위한 네트워크 입문',8);
insert into tblBook (bookSeq,bookName,publisherSeq) values (7,'개발자의 글쓰기',10);
insert into tblBook (bookSeq,bookName,publisherSeq) values (8,'당신이 지금 알아야 할 AWS',9);
insert into tblBook (bookSeq,bookName,publisherSeq) values (9,'그로스 해킹(Growth Hacking)',8);
insert into tblBook (bookSeq,bookName,publisherSeq) values (10,'개발자도 궁금한 IT 인프라',7);
insert into tblBook (bookSeq,bookName,publisherSeq) values (11,'Java의 정석',11);
insert into tblBook (bookSeq,bookName,publisherSeq) values (12,'Do it! C언어 입문',3);
insert into tblBook (bookSeq,bookName,publisherSeq) values (13,'윤성우의 열혈 C++ 프로그래밍',12);
insert into tblBook (bookSeq,bookName,publisherSeq) values (14,'이것이 C# 이다',4);
insert into tblBook (bookSeq,bookName,publisherSeq) values (15,'Do it! 점프 투 파이썬',3);
insert into tblBook (bookSeq,bookName,publisherSeq) values (16,'SQL 레벨업',4);
insert into tblBook (bookSeq,bookName,publisherSeq) values (17,'Git 교과서',8);
insert into tblBook (bookSeq,bookName,publisherSeq) values (18,'이야기로 다가가는 HTML',9);
insert into tblBook (bookSeq,bookName,publisherSeq) values (19,'STYLIN WITH CSS',14);
insert into tblBook (bookSeq,bookName,publisherSeq) values (20,'초보자를 위한 JSP 프로그래밍',15);
insert into tblBook (bookSeq,bookName,publisherSeq) values (21,'자바 ORM 표준 JPA 프로그래밍',16);
insert into tblBook (bookSeq,bookName,publisherSeq) values (22,'예제로 배우는 스프링 부트 입문',9);
insert into tblBook (bookSeq,bookName,publisherSeq) values (23,'손에 잡히는 R 프로그래밍',13);
insert into tblBook (bookSeq,bookName,publisherSeq) values (24,'이것이 우분투 리눅스다',13);
insert into tblBook (bookSeq,bookName,publisherSeq) values (25,'Do it! 안드로이드 앱 프로그래밍',3);
insert into tblBook (bookSeq,bookName,publisherSeq) values (26,'시작하세요 iOS 6 프로그래밍',10);
insert into tblBook (bookSeq,bookName,publisherSeq) values (27,'이펙티브 타입스크립트',2);
insert into tblBook (bookSeq,bookName,publisherSeq) values (28,'Hadoop 에코시스템',16);
insert into tblBook (bookSeq,bookName,publisherSeq) values (29,'ASP 웹 프로그래밍',17);
insert into tblBook (bookSeq,bookName,publisherSeq) values (30,' PHP+MySQL 입문',18);