INSERT INTO	TBLQUESTION	VALUES (	1	,  '자바에 대해서 설명할 수 있다.	'  ,	1	);
INSERT INTO	TBLQUESTION	VALUES (	2	,  '컴파일러에 대해서 설명할 수 있다.	'  ,	2	);
INSERT INTO	TBLQUESTION	VALUES (	3	,  '자바의 자료형에 대해서 설명할 수 있다.	'  ,	3	);
INSERT INTO	TBLQUESTION	VALUES (	4	,  '자바의 자료형은 참조형과 값형으로 나눈다. 참조형은 값의 크기에 따라 공간의 크기 변화가 없고, 값형은 값의 크기에 따라 공간의 크기가 변화한다.'  ,	4	);
INSERT INTO	TBLQUESTION	VALUES (	5	,  'int는 실수형이고, 8byte의 크기를 가진다.	'  ,	5	);
INSERT INTO	TBLQUESTION	VALUES (	6	,  'float는 실수형이고, 4byte의 크기를 가진다.	'  ,	6	);
INSERT INTO	TBLQUESTION	VALUES (	7	,  'char는 문자를 1개 저장할 수 있고, 1byte의 크기를 가진다.	'  ,	7	);
INSERT INTO	TBLQUESTION	VALUES (	8	,  '컴파일러에 대해서 설명할 수 있다.	'  ,	8	);
INSERT INTO	TBLQUESTION	VALUES (	9	,  'int num = 10000000000; //이 코드는 실행이 가능하다.	'  ,	9	);
INSERT INTO	TBLQUESTION	VALUES (	10	,  'char c = "A"; //이 코드는 실행이 가능하다.	'  ,	10	);
INSERT INTO	TBLQUESTION	VALUES (	11	,  'System.out.print("10 + 20 = " + 10 + 20); //이 코드의 결과는 "10 + 20 = 30"이다.		'  ,	11	);
INSERT INTO	TBLQUESTION	VALUES (	12	,  'System.out.print(010); //이 코드의 결과는 8이다.	'  ,	12	);
INSERT INTO	TBLQUESTION	VALUES (	13	,  'System.out.printf("이름: %d\n", "홍길동"); //이 코드는 실행이 가능하다.	'  ,	13	);
INSERT INTO	TBLQUESTION	VALUES (	14	,  'System.out.print(), System.out.println(), System.out.printf()에 대해서 설명할 수 있다.	'  ,	14	);
INSERT INTO	TBLQUESTION	VALUES (	15	,  'printf() 메소드의 %s, %d, %f, %c, %b에 대해서 설명할 수 있다.	'  ,	15	);
INSERT INTO	TBLQUESTION	VALUES (	16	,  'System.in.read()의 동작원리에 대해서 설명할 수 있다.	'  ,	16	);
INSERT INTO	TBLQUESTION	VALUES (	17	,  '산술 연산자에 대해서 설명할 수 있다.	'  ,	17	);
INSERT INTO	TBLQUESTION	VALUES (	18	,  '비교 연산자에 대해서 설명할 수 있다.	'  ,	18	);
INSERT INTO	TBLQUESTION	VALUES (	19	,  '논리 연산자에 대해서 설명할 수 있다.	'  ,	19	);
INSERT INTO	TBLQUESTION	VALUES (	20	,  '대입 연산자에 대해서 설명할 수 있다.	'  ,	20	);
INSERT INTO	TBLQUESTION	VALUES (	21	,  '조건 연산자에 대해서 설명할 수 있다.	'  ,	21	);
INSERT INTO	TBLQUESTION	VALUES (	22	,  '연산자 우선 순위에 대해서 설명할 수 있다.	'  ,	22	);
INSERT INTO	TBLQUESTION	VALUES (	23	,  '연산 방향 대해서 설명할 수 있다.	'  ,	23	);
INSERT INTO	TBLQUESTION	VALUES (	24	,  '대입 연산자는 우선 순위가 가장 낮다.	'  ,	24	);
INSERT INTO	TBLQUESTION	VALUES (	25	,  '비교 연산자는 우선 순위가 가장 높다.	'  ,	25	);
INSERT INTO	TBLQUESTION	VALUES (	26	,  '값형 형변환에 대해 설명할 수 있다.	'  ,	26	);
INSERT INTO	TBLQUESTION	VALUES (	27	,  '오버플로우, 언더플로우에 대해서 설명할 수 있다.	'  ,	27	);
INSERT INTO	TBLQUESTION	VALUES (	28	,  '명시적인 형변환은 항상 안전하다.	'  ,	28	);
INSERT INTO	TBLQUESTION	VALUES (	29	,  'long을 float로 형변환할 때 암시적인 형변환이 일어난다.'  ,	29	);
INSERT INTO	TBLQUESTION	VALUES (	30	,  '컴파일 오류, 런타임 오류, 논리 오류를 구분해서 설명할 수 있다.'  ,	30	);
INSERT INTO	TBLQUESTION	VALUES (	31	,  '메소드의 목적에 대해서 설명할 수 있다.	'  ,	31	);
INSERT INTO	TBLQUESTION	VALUES (	32	,  '메소드 인자리스트의 역할을 설명할 수 있다.'  ,	32	);
INSERT INTO	TBLQUESTION	VALUES (	33	,  '메소드 반환값의 역할을 설명할 수 있다.	'  ,	33	);
INSERT INTO	TBLQUESTION	VALUES (	34	,  '메소드 오버로딩에 대해서 설명할 수 있다.'  ,	34	);
INSERT INTO	TBLQUESTION	VALUES (	35	,  '재귀 메소드에 대해서 설명할 수 있다.'  ,	35	);
INSERT INTO	TBLQUESTION	VALUES (	36	,  '프로젝트 담당 업무 구현 시 메소드 오버로딩을 한적이 있다.	'  ,	36	);
INSERT INTO	TBLQUESTION	VALUES (	37	,  '프로젝트 담당 업무 구현 시 재귀 메소드를 구현한 적이 있다.	'  ,	37	);
INSERT INTO	TBLQUESTION	VALUES (	38	,  '지역 변수에 대해서 설명할 수 있다.	'  ,	38	);
INSERT INTO	TBLQUESTION	VALUES (	39	,  '지역 변수의 생명 주기에 대해서 설명할 수 있다.	'  ,	39	);
INSERT INTO	TBLQUESTION	VALUES (	40	,  '지역 변수는 개발자가 초기화를 하지 않아서 사용이 가능하다.	'  ,	40	);
INSERT INTO	TBLQUESTION	VALUES (	41	,  '메소드 오버로딩은 반환값의 타입이 중요하다.	'  ,	41	);
INSERT INTO	TBLQUESTION	VALUES (	42	,  'Calendar 클래스에 대해서 설명하고 조작할 수 있다.	'  ,	42	);
INSERT INTO	TBLQUESTION	VALUES (	43	,  '시각 - 시각의 결과는 시간이다.'  ,	43	);
INSERT INTO	TBLQUESTION	VALUES (	44	,  'Calendar에서 특정 시간을 뺄 때 add() 메소드를 사용한다.	'  ,	44	);
INSERT INTO	TBLQUESTION	VALUES (	45	,  'if문을 잘 다룰 수 있다.	'  ,	45	);
INSERT INTO	TBLQUESTION	VALUES (	46	,  'for문을 잘 다룰 수 있다.	'  ,	46	);
INSERT INTO	TBLQUESTION	VALUES (	47	,  '다중 for문을 잘 다룰 수 있다.	'  ,	47	);
INSERT INTO	TBLQUESTION	VALUES (	48	,  'while문을 잘 다룰 수 있다.	'  ,	48	);
INSERT INTO	TBLQUESTION	VALUES (	49	,  'break, continue문을 잘 다룰 수 있다.	'  ,	49	);