
-- A.01
-- 기초 정보 관리


-- 출력
SELECT 
	pl.PROCEDURENAME AS "과정명", 
	s.SUBJECTNAME AS "과목명", 
	r.ROOMNAME AS "강의실명",
	r.ROOMSUM AS "강의실정원", 
	b.BOOKNAME AS "교재명", 
	p.PUBLISHERNAME AS "출판사명"
FROM TBLPROCEDURESUBJECT ps
	INNER JOIN TBLSUBJECT s
		ON ps.SUBJECTSEQ = s.SUBJECTSEQ
			INNER JOIN TBLBOOKLIST bl
				ON s.SUBJECTSEQ = bl.SUBJECTSEQ
					INNER JOIN TBLBOOK b
						ON bl.BOOKSEQ = b.BOOKSEQ
							INNER JOIN TBLPUBLISHER p
								ON b.PUBLISHERSEQ = p.PUBLISHERSEQ
									INNER JOIN TBLPROCEDURELIST pl
										ON ps.PROCEDURELISTSEQ = pl.PROCEDURELISTSEQ
											INNER JOIN TBLOPENINGPROCEDURE op
												ON pl.PROCEDURELISTSEQ = op.PROCEDURELIST
													INNER JOIN TBLROOM r
														ON op.ROOMSEQ = r.ROOMSEQ;
														
						
-- 입력
INSERT INTO TBLPROCEDURELIST VALUES ((SELECT max(PROCEDURELISTSEQ)+1 FROM TBLPROCEDURELIST) , '과정명');
INSERT INTO TBLSUBJECT VALUES (seqSubject.nextVal, '과목명');
INSERT INTO TBLROOM VALUES ((SELECT max(ROOMSEQ)+1 FROM TBLROOM), '강의실명', '정원');
INSERT INTO TBLBOOK VALUES ((SELECT max(BOOKSEQ)+1 FROM TBLBOOK), '교재명', '출판사번호');
INSERT INTO TBLPUBLISHER VALUES ((SELECT max(PUBLISHERSEQ)+1 FROM TBLPUBLISHER), '출판사명');

-- 수정
UPDATE TBLPROCEDURELIST SET PROCEDURENAME = '과정명' WHERE PROCEDURENAME = '과정명';
UPDATE TBLSUBJECT SET SUBJECTNAME = '과목명' WHERE SUBJECTNAME = '과목명';
UPDATE TBLROOM SET ROOMNAME = '강의실명' WHERE ROOMNAME = '강의실명';
UPDATE TBLBOOK SET BOOKNAME = '교재명' WHERE BOOKNAME = '교재명';
UPDATE TBLPUBLISHER SET PUBLISHERNAME = '출판사명' WHERE PUBLISHERNAME = '출판사명';

-- 삭제
DELETE FROM TBLPROCEDURELIST WHERE PROCEDURENAME = '과정명';
DELETE FROM TBLSUBJECT WHERE SUBJECTNAME = '과목명';
DELETE FROM TBLROOM WHERE ROOMNAME = '강의실명';
DELETE FROM TBLBOOK WHERE BOOKNAME = '교재명';
DELETE FROM TBLPUBLISHER WHERE PUBLISHERNAME = '출판사명';


